stages:
  - build
  - test
  - deploy

cache:
  paths:
    - target/

build:
  image: maven:latest
  stage: build
  script:
    - "mvn clean package --batch-mode -DskipTests"

iqscan:
  image: sonatype/gitlab-nexus-iq-pipeline:latest
  stage: test
  script:
    - |
      SCAN_STAGE="build"
      if [ "$CI_COMMIT_BRANCH" != "main" ]; then
        SCAN_STAGE="develop"
      fi
      echo "Scanning with stage: $SCAN_STAGE"
      #/sonatype/evaluate -i test3proj__test334913 -t $SCAN_STAGE -rn gitlab-ci-policy-eval-report.html -r scan-result.json -c target/*.jar
      /sonatype/evaluate -i test3proj__test334913 -t $SCAN_STAGE -rn gitlab-ci-policy-eval-report.html -c target/*.jar
  artifacts:
    when: always
    #reports:
     # dotenv: evaluate.env
    paths:
      # - scan-result.json
      - gitlab-ci-policy-eval-report.html

